# Use the official Python base image
FROM python:3.9-slim

# Set the working directory inside the container
WORKDIR /app

# Install necessary packages, including cron
RUN apt-get update && apt-get install -y cron procps openssl

# Copy the requirements.txt file into the container
COPY requirements.txt /app/requirements.txt

# Install the necessary Python libraries
RUN pip install --no-cache-dir -r /app/requirements.txt

# Copy the entire project into the container
COPY app/crawler.py /app/crawler.py
COPY app/appstart.sh /app/appstart.sh

# Expose ports
EXPOSE 5432
EXPOSE 8000
EXPOSE 8001

# Create the log file and set permissions
RUN touch /var/log/crawler.log && chmod 666 /var/log/crawler.log

# Add the cron job
RUN echo "0 */3 * * * /usr/local/bin/python3 /app/crawler.py 2>&1 | tee -a /var/log/crawler.log > /proc/1/fd/1" >> /etc/cron.d/crawler

# Apply cron job
RUN chmod 0664 /etc/cron.d/crawler && crontab /etc/cron.d/crawler

# Set entrypoint script
COPY docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh
RUN chmod +x /usr/local/bin/docker-entrypoint.sh

# Start cron and API page.
RUN chmod +x /app/appstart.sh

# Command to start the service
CMD ["bash", "/app/appstart.sh"]
